---
title: "Bird Joins"
author: "Jaslyn Miura"
format: html
---

```{r}

library(tidyverse)
library(lubridate)
library(here)

```

```{r}

bird_observations <- read_csv(here("data", "52_pp52_birds_1.csv"))
sites <- read_csv(here("data", "52_pp52_sites_1.csv"))
surveys <- read_csv(here("data", "52_pp52_surveys_1.csv"))
taxalist <- read_csv(here("data", "52_pp52_taxalist_1.csv"))

```

```{r}

birds_subset <- bird_observations %>% 
  filter(species_id %in% c("BHCO", "RWBL") & site_id %in% c("LI-W", "NU-C"))

```

```{r}

# left_join() practice

birds_left <- birds_subset %>% 
  left_join(sites, by = "site_id") %>%
  left_join(taxalist, by = "species_id")

```

```{r}

# full_join() practice

birds_full <- birds_subset %>% 
  full_join(sites, by = "site_id")

```


```{r}

task2_birds <- bird_observations %>% 
  rename(bird_obs_notes = notes) %>% 
  left_join(taxalist, by = "species_id") %>% 
  left_join(sites, by = "site_id") %>% 
  left_join(surveys, by = "survey_id") %>% 
  select(survey_date, common_name, park_name) %>% 
  mutate(survey_month = lubridate::month(survey_date)) %>% 
  mutate(survey_month = as.factor(survey_month)) %>% 
  dplyr::relocate(survey_month, .after = survey_date) %>% 
  group_by(park_name, survey_month) %>% 
  summarize(total_count = n()) %>% 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa"))

```


