---
title: "String Practice"
author: "Jaslyn Miura"
format: html
---

```{r}

alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am -- HVAC system down, facilities management alerted",
                       "8:24am -- Elevator North out of service",
                       "12:41am -- Fire alarm, UCSB fire responded and cleared",
                       "9:58pm -- Campus point emergency siren, UCPD responded")
)

```

```{r}

# task 3

alarm_report %>% 
  mutate(building = str_replace(building, pattern = "Engineering", replacement = "Engr")) %>% 
  separate(col = building, 
           into = c("building", "wing"),
           sep = "-") %>% 
  filter(str_detect(alarm_message, "responded")) %>% 
  separate(col = alarm_message,
           into = c("time", "message"),
           sep = "--") %>% 
  mutate(date = lubridate::ymd(date))
  
```

